services:
  elasticsearch:
    container_name: db_product
    image: elasticsearch:8.19.5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.types-single-node
    networks:
      - redeecommerce

  ms-product:
    container_name: ms-product
    build: .
    ports:
      - "8082:8082"
    depends_on:
      elasticsearch:
        condition: service_started
    restart: always

    networks:
      - redeecommerce

networks:
  redeecommerce:
    driver: bridge