services:
  configserver:
    container_name: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - redeecommerce

networks:
  redeecommerce:
    driver: bridge
