FROM maven:3.9.0-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

# ------------------------------
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/user-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java" , "-jar", "app.jar"]