server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db_ms_user:5432/usersdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqp://admin:admin@localhost:5672

broker:
  queue:
    email:
      name: default.email
